---
title: "Puerto Rico Migration Flows: Proposal Feedback"
date: 2022-11-10
author: "Eli Pousson"
---

This proposal is a solid start! Here are some comments explaining the changes I just committed to your project repository and a few requests for additional updates.

## Changes I made and why

-   I added descriptive headings to break up large blocks of text, added a title, and fixed some minor formatting issues. You should always have a space between a heading tag, e.g. `##` and the heading text.
-   I removed extraneous code that you brought in from the tidycensus vignette, e.g. you pulled data on population for all U.S. states which isn't relevant for your analysis. You also had included the code from the project setup instructions - those functions are only intended to be run *once* and shouldn't be included in a document that you may run again and again as you (or others reproduce your analysis).
-   I removed your API key. You should never commit your API key to a repository -- it is private and keyed to your individual email. Once your run the census_api_key function it is saved locally. I use my *own* key to access the Census API.
-   I added an example showing how you can use the `purrr::map_dfr()` function (see chunks 3 and 4) to loop over a vector of county FIPS numbers (from tigris) and create a single combined data frame for the flows data. It is much more compact (a dozen lines instead of hundreds) and keeps the data in a single object rather than over 75. You could use a similar approach to get data for multiple years.

## Changes you need to make

-   Add the missing file for `FEMANFIPClaims_PR.xlsx` is missing from the repository and update your code to show that you can read the data and convert the data into a spatial format.
-   Be clear and accurate about what data you are using. `get_estimates()` gives you data from the [Census Bureau's Population Estimates Program](https://www.census.gov/programs-surveys/popest.html) (PEP) but you have it below a heading "ACS estimates". ACS and PEP are separate programs. Use the `get_acs()` function to download ACS data.
-   When you filter out the `NA` values for GEOID2, you're excluding migration from Puerto Rico to other countries outside the U.S. That is fine to do *but* you need to say you're doing that if that is your intent when you further develop the analysis.
-   Fill out your README with some basic information about your project (reusing text from your proposal where it make sense). Imagine you're trying to briefly explain the project to another student interested in doing a similar project and show where they can access the same data you are using. Once you fill in some information, don't forget to render the Rmd file using `knitr::knit("README.Rmd")`. You'll need to go back and expand the README later on when you further develop your analysis. Check out Reina's [slides from back in September](https://raw.githubusercontent.com/reinacmurray/documenting-spatial-data-class/main/Presentation/Documenting%20Spatial%20Data.pdf) for more tips on writing READMEs for data projects.

## Things to think about

-   Make sure your data is accessible if you want to use it. The link for your hospital data (which I understand you may not be using for this analysis) is for a map and the underlying layers don't appear to be public.
-   Do more than just read in the data! Your code shows that you're able to read in the flows data but you should add some limited data visualization up top. Consider using the PEP data to create a bar chart showing age, race, or sex distributions or creating a map showing the combined "moved out" vs. combined "moved in" for each county in Puerto RIco. Can you join spatial data to the flows data showing the locations where people are moving to?
-   Your first two questions are clear and specific but the third question in your proposal (Can I use flooding claims information to inform migration flow?) is unclear. What do you mean by inform migration flow? In addition, try to explain why these three questions matter to your study (or to the people of Puerto Rico). Are you trying to identify the year with the most migration to see if migration increases after the hurricanes? If so, say that *and* reference any studies that have already looked at the topic.
-   As we dicussed during our conversation, using the 5-year ACS data is difficult for a pre- and post-hurricane comparison but there are also 3-year and 1-year samples (look at the survey parameter for `get_acs()` to see how to access the other survey datasets). The geographic availability and margin-of-error varies by survey -- so try exploring this option now and see if it is feasible to use for a pre-post comparison.
